"""Generate static TTF instances of our web fonts for PDF embedding.

Our self-hosted web fonts are VARIABLE woff2 files. pdf-lib/fontkit cannot map
glyphs in a variable font — every glyph resolves to id 0, so text embedded in a
PDF extracts as NUL bytes (the same failure users hit with Firefox's print
backend, issue #4). Instancing each font at a fixed weight produces a plain
static TTF that embeds with a correct ToUnicode map.

The index is keyed by the CSS family name (e.g. `source-sans-3`), not by
anything guessed from the font file's internal name records — per-weight
Google Fonts files often bake the style into nameID 1/16 (e.g. "Source Sans 3
ExtraLight"), which does not match what `getComputedStyle().fontFamily`
reports for elements styled from our CSS. `src/styles/fonts.css` (generated by
scripts/fetch-fonts.cjs) is the single source of truth linking a CSS family
name + weight to a font file, so we parse it directly.

Build-time only: fontTools is never shipped to the browser. Output goes to
public/fonts-pdf/ and is fetched on demand at export time (same-origin).

Usage:  python scripts/make-pdf-fonts.py
"""

from __future__ import annotations

import json
import os
import pathlib
import re
import sys
import tempfile
from io import BytesIO

from fontTools.merge import Merger
from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

CSS = pathlib.Path("src/styles/fonts.css")
PUBLIC = pathlib.Path("public")
OUT = pathlib.Path("public/fonts-pdf")

# A generated directory should be verifiable: rebuild it, and an empty diff
# should mean nothing changed. Without this, every rebuild rewrites the `head`
# table's build timestamp in all 158 files and git reports 158 modifications
# that mean nothing - noise a real change can hide in, which is how a broken
# short-loca trim once got through. fontTools reads this variable for that
# timestamp. The value is arbitrary and fixed; only its constancy matters.
os.environ.setdefault("SOURCE_DATE_EPOCH", "1700000000")

FONT_FACE_RE = re.compile(r"@font-face\s*\{([^}]*)\}", re.DOTALL)
FAMILY_RE = re.compile(r"font-family:\s*'([^']*)'")
STYLE_RE = re.compile(r"font-style:\s*(\S+?);")
WEIGHT_RE = re.compile(r"font-weight:\s*(\d+)\s*;")
SRC_RE = re.compile(r"url\((/fonts/[^)]+\.woff2)\)")


def family_slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", (name or "").lower()).strip("-")


def parse_font_faces(css_text: str) -> list[tuple[str, int, str, str]]:
    """Return (family, weight, style, /fonts/<file>.woff2) for every @font-face block."""
    out = []
    for block in FONT_FACE_RE.findall(css_text):
        family_m = FAMILY_RE.search(block)
        style_m = STYLE_RE.search(block)
        weight_m = WEIGHT_RE.search(block)
        src_m = SRC_RE.search(block)
        if not (family_m and style_m and weight_m and src_m):
            continue
        out.append((family_m.group(1), int(weight_m.group(1)), style_m.group(1), src_m.group(1)))
    return out


# Google serves each family as SEVERAL woff2 subsets (latin, latin-ext, ...).
# They are disjoint on-disk, but the BROWSER unions them at render time via
# each @font-face block's unicode-range, so a résumé using Polish/Czech/
# Hungarian/Croatian/Turkish letters renders correctly on screen. A static
# PDF-embeddable TTF can't do that per-run unicode-range trick, so below we
# MERGE every subset file for a (family, weight) into one TTF instead of
# picking a single winner (see the merge loop in main()). coverage() is still
# used to rank candidates — merge order matters (best-coverage file first
# keeps its metrics/naming as the merged font's base) and it doubles as the
# fallback if merging a family's subsets fails.
REQUIRED_CHARS = (
    [ord(c) for c in "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"]
    + [ord(c) for c in " .,;:!?'\"()[]{}/\\|&@#%$+-*=<>_~^`"]
    + [0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2022, 0x00B7, 0x2026]  # – — ‘ ’ “ ” • · …
    + list(range(0x00C0, 0x0100))  # Latin-1 accented letters
    + [0x0105, 0x0107, 0x010D, 0x0119, 0x0151, 0x0159, 0x015F, 0x017E, 0x0142, 0x0111, 0x0131, 0x0130, 0x011F]
    # ą           ć           č           ę           ő           ř           ş           ž           ł           đ           ı           İ           ğ
    # Latin Extended-A (Central European / Turkish) — the charset harness's
    # latin-ext must-pass corpus. These live in the `latin-ext` Google subset
    # file, never the `latin` one, so before this fix they never contributed
    # to coverage() and `latin` always "won" a selection that no longer
    # exists (we merge instead of selecting).
)


# Static outputs this script does not build itself, by index key.
EXTRA_STATIC = {"cvaurum-marks|400": "cva-marks-400.ttf"}


def coverage(font: TTFont) -> int:
    try:
        cmap = font.getBestCmap()
    except Exception:  # noqa: BLE001
        return 0
    return sum(1 for cp in REQUIRED_CHARS if cp in cmap)


def instance_static(font_path: pathlib.Path, weight: int, label: str) -> TTFont | None:
    """Load font_path and return a static (non-variable) TTFont instanced at
    `weight`. fontTools.merge.Merger cannot handle variable fonts, so every
    subset candidate must be instanced BEFORE merging (per-family, not just
    the eventual winner). Returns None on failure so the caller can drop this
    one candidate without aborting the whole (family, weight) group."""
    try:
        font = TTFont(font_path)
    except Exception as exc:  # noqa: BLE001 - report and continue
        print(f"  skip {font_path.name}: {exc}")
        return None
    try:
        if "fvar" in font:
            axes = {a.axisTag: (a.minValue, a.maxValue) for a in font["fvar"].axes}
            lo, hi = axes.get("wght", (weight, weight))
            target = min(max(weight, lo), hi)
            if target != weight:
                print(f"  warn {label}: weight {weight} outside wght axis [{lo},{hi}], using {target}")
            font = instancer.instantiateVariableFont(
                font, {"wght": target}, inplace=True, updateFontNames=False
            )
        font.flavor = None  # plain TTF, not woff2
        return font
    except Exception as exc:  # noqa: BLE001
        print(f"  fail instancing {font_path.name}: {exc}")
        return None


SCRIPT_SETS: list[tuple[str, object]] = [
    # Widest first: each output keeps the most coverage that still fits the
    # short loca format. Ranges are the scripts the app claims to support.
    ("all scripts", None),
    (
        "latin, greek, cyrillic, vietnamese",
        lambda c: c < 0x0250
        or 0x0300 <= c <= 0x036F
        or 0x0370 <= c <= 0x03FF
        or 0x0400 <= c <= 0x052F
        or 0x1E00 <= c <= 0x1EFF
        or 0x2000 <= c <= 0x206F
        or 0x20A0 <= c <= 0x20BF
        or c in (0x2122, 0x2212),
    ),
    (
        "latin, vietnamese",
        lambda c: c < 0x0250
        or 0x0300 <= c <= 0x036F
        or 0x1E00 <= c <= 0x1EFF
        or 0x2000 <= c <= 0x206F
        or 0x20A0 <= c <= 0x20BF
        or c in (0x2122, 0x2212),
    ),
    (
        "latin",
        lambda c: c < 0x0250 or 0x2000 <= c <= 0x206F or 0x20A0 <= c <= 0x20BF or c in (0x2122, 0x2212),
    ),
]


def to_short_loca(font: TTFont, label: str) -> TTFont:
    """Return `font` on the SHORT loca format, trimming scripts only as needed.

    fontkit's subsetter — the one pdf-lib runs when we embed with
    `subset: true` — produces a broken glyf table for a source font on the LONG
    loca format (`head.indexToLocFormat == 1`). The PDF still carries correct,
    extractable text and a correct ToUnicode map, so every text-layer check
    passes; it simply draws almost none of the glyphs. Four families shipped
    that way (Tinos, Arimo, EB Garamond, Cormorant Garamond) and seven
    templates exported an unreadable résumé.

    Short loca stores each glyph offset as a uint16 of half-offsets, so it can
    only address ~128 KB of glyf. Whether a font fits is a property of its
    outlines, not of its codepoint count: Tinos keeps every script and fits,
    while Cormorant Garamond's heavier outlines fit only Latin. So the sets
    above are tried widest-first and the first that fits is kept — a family
    loses coverage only when its own outlines leave no choice, and the script
    fallback chain (src/data/fonts.ts) carries anything dropped.
    """
    # Bake before believing it. `indexToLocFormat` is recalculated when the
    # glyf table is COMPILED, so a merged font reports whatever its source
    # carried until it is written - and a font that reports 0 here can still
    # land on disk as 1. Asking the in-memory value let this exit fire on
    # fourteen families that then shipped long loca. Same round trip the loop
    # below uses, for the same reason.
    probe = TTFont(BytesIO(_as_bytes(font)))
    already_short = probe["head"].indexToLocFormat == 0
    probe.close()
    if already_short:
        return font
    covered = set(font.getBestCmap().keys())
    for name, pred in SCRIPT_SETS:
        if pred is None:
            continue
        keep = [c for c in covered if pred(c)]
        if not keep:
            continue
        trial = TTFont(BytesIO(_as_bytes(font)))
        opts = subset.Options()
        opts.notdef_outline = True
        opts.layout_features = ["*"]
        sub = subset.Subsetter(options=opts)
        sub.populate(unicodes=keep)
        sub.subset(trial)
        # fontTools recalculates indexToLocFormat when it COMPILES the glyf
        # table, not when the subsetter finishes, so the only honest way to
        # ask "does this fit short loca?" is to save it and read it back.
        baked = TTFont(BytesIO(_as_bytes(trial)))
        trial.close()
        if baked["head"].indexToLocFormat == 0:
            print(f"  {label}: long loca -> short, keeping {name}")
            return baked
        baked.close()
    print(f"  {label}: WARNING still long loca after every trim - fontkit will drop its glyphs")
    return font


def _as_bytes(font: TTFont) -> bytes:
    buf = BytesIO()
    font.save(buf)
    return buf.getvalue()


def main() -> int:
    if not CSS.is_file():
        print(f"no generated stylesheet: {CSS}", file=sys.stderr)
        return 1
    OUT.mkdir(parents=True, exist_ok=True)

    faces = parse_font_faces(CSS.read_text(encoding="utf-8"))
    print(f"{len(faces)} @font-face blocks")

    # We do not embed italic faces yet (the painter has no italic path).
    faces = [f for f in faces if f[2] == "normal"]

    # Group by (family, weight) — usually several unicode-subset blocks each.
    groups: dict[tuple[str, int], list[str]] = {}
    for family, weight, _style, src in faces:
        groups.setdefault((family, weight), []).append(src)

    print(f"{len(groups)} (family, weight) pairs")

    index: dict[str, str] = {}
    seen_static: set[str] = set()

    merge_failures: list[str] = []

    for (family, weight), srcs in sorted(groups.items()):
        slug = family_slug(family)
        if not slug:
            print(f"  skip {family!r} {weight}: no usable slug")
            continue

        label = f"{slug}-{weight}"

        # Instance EVERY unicode-subset file for this (family, weight) — not
        # just the best one. Google's subsets are disjoint (latin has ASCII,
        # latin-ext has Central European letters, neither has both), so we
        # need all of them in hand to merge below.
        candidates: list[tuple[int, pathlib.Path, TTFont]] = []
        for src in dict.fromkeys(srcs):  # de-dupe, keep order
            font_path = PUBLIC / src.lstrip("/")
            inst = instance_static(font_path, weight, label)
            if inst is None:
                continue
            candidates.append((coverage(inst), font_path, inst))

        if not candidates:
            print(f"  skip {label}: no readable source file")
            continue

        # Best coverage first: this is the merge base (Merger keeps the
        # first font's metrics/naming) and also the single-file fallback if
        # merging fails outright.
        candidates.sort(key=lambda c: c[0], reverse=True)
        best_score = candidates[0][0]
        if best_score < 60:
            print(f"  warn {label}: low glyph coverage ({best_score}/{len(REQUIRED_CHARS)})")

        key = f"{slug}|{weight}"
        out_name = f"{label}.ttf"

        if len(candidates) == 1:
            merged: TTFont | None = candidates[0][2]
        else:
            merged = None
            try:
                # pyftmerge's designed use case: joining disjoint-coverage
                # subsets of the same family into one font. Merger._openFonts
                # reopens its input list from scratch (by path) TWICE per
                # merge() call, so real temp files are required here — handing
                # it in-memory buffers would read past EOF on the second pass.
                with tempfile.TemporaryDirectory(prefix="pdf-fonts-merge-") as tmp:
                    tmp_paths = []
                    for i, (_score, _path, inst) in enumerate(candidates):
                        p = pathlib.Path(tmp) / f"{i}.ttf"
                        inst.save(p)
                        tmp_paths.append(str(p))
                    merged = Merger().merge(tmp_paths)
                    merged.flavor = None
            except Exception as exc:  # noqa: BLE001
                # Merging can fail on GSUB/glyph-name conflicts between a
                # family's subset files. Never silently drop latin-ext
                # coverage: warn loudly and fall back to the best single
                # subset (pre-fix behaviour) instead of aborting the run.
                print(f"  warn {label}: merge failed ({exc}), latin-ext dropped")
                merge_failures.append(label)
                merged = candidates[0][2]

        for _score, _path, inst in candidates:
            if inst is not merged:
                inst.close()

        merged = to_short_loca(merged, out_name)
        try:
            merged.save(OUT / out_name)
            merged.close()
        except Exception as exc:  # noqa: BLE001
            print(f"  fail {out_name}: {exc}")
            continue
        index[key] = out_name
        seen_static.add(out_name)

    if merge_failures:
        print(f"\n{len(merge_failures)} family/weight pair(s) fell back to single-subset (latin-ext dropped):")
        for label in merge_failures:
            print(f"  - {label}")

    # The marks font is not instanced from a web font - it is generated
    # outright by scripts/make-marks-font.py, because the four bullet glyphs
    # it carries (U+25E6 white bullet, U+25AA small square, U+2713 check,
    # U+25C6 diamond) are in NONE of the bundled families. Named here so the
    # index finds it and the stale sweep below leaves it alone.
    for key, name in EXTRA_STATIC.items():
        if (OUT / name).exists():
            index[key] = name
            seen_static.add(name)
        else:
            print(f"  WARNING {name} missing - run scripts/make-marks-font.py")

    # Drop stale outputs from earlier runs so the directory always matches the
    # index exactly (family slugs can change as the generator improves).
    for stale in OUT.glob("*.ttf"):
        if stale.name not in seen_static:
            stale.unlink()
            print("  removed stale", stale.name)

    (OUT / "index.json").write_text(json.dumps(index, indent=1, sort_keys=True), encoding="utf-8")
    total_kb = sum((OUT / f).stat().st_size for f in seen_static) // 1024
    print(f"wrote {len(index)} static fonts ({total_kb} KB) -> {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
