/**
 * Curated font registry — a broad set of the strongest, ATS-safe resume
 * typefaces. All families are SELF-HOSTED: the woff2
 * files live in public/fonts/ and their @font-face rules are in
 * src/styles/fonts.css (generated by scripts/fetch-fonts.cjs). The app makes
 * ZERO external font requests — nothing is fetched from Google. Because the live
 * preview and the native print render in the SAME browser, the printed PDF is
 * byte-identical to the preview.
 */

export type FontCategory = 'sans' | 'serif' | 'mono' | 'display' | 'handwriting'

export interface FontDef {
  /** Display + CSS family name */
  name: string
  category: FontCategory
  /** Google Fonts family query (defaults to name) */
  family?: string
  /** Weights to request */
  weights?: number[]
  /** Italic axis available */
  italic?: boolean
  /** CSS fallback stack */
  fallback?: string
}

export const FONTS: FontDef[] = [
  // — Sans —
  { name: 'Inter', category: 'sans', weights: [400, 500, 600, 700, 800] },
  { name: 'Roboto', category: 'sans' },
  { name: 'Open Sans', category: 'sans' },
  { name: 'Lato', category: 'sans', weights: [400, 700, 900] },
  { name: 'Montserrat', category: 'sans', weights: [400, 500, 600, 700, 800] },
  { name: 'Raleway', category: 'sans' },
  { name: 'Rubik', category: 'sans' },
  { name: 'Poppins', category: 'sans' },
  { name: 'Work Sans', category: 'sans' },
  { name: 'Source Sans 3', category: 'sans' },
  { name: 'Nunito Sans', category: 'sans' },
  { name: 'Mulish', category: 'sans' },
  { name: 'Karla', category: 'sans' },
  { name: 'Figtree', category: 'sans' },
  { name: 'PT Sans', category: 'sans', weights: [400, 700] },
  { name: 'Arimo', category: 'sans' },
  { name: 'Chivo', category: 'sans' },
  { name: 'Exo 2', category: 'sans' },
  { name: 'IBM Plex Sans', category: 'sans' },
  { name: 'DM Sans', category: 'sans' },

  // — Serif —
  { name: 'Merriweather', category: 'serif', weights: [400, 700, 900] },
  { name: 'Lora', category: 'serif' },
  { name: 'PT Serif', category: 'serif', weights: [400, 700] },
  { name: 'Playfair Display', category: 'serif', weights: [400, 500, 600, 700, 800] },
  { name: 'Source Serif 4', category: 'serif' },
  { name: 'Roboto Slab', category: 'serif' },
  { name: 'Bitter', category: 'serif' },
  { name: 'Tinos', category: 'serif', weights: [400, 700] },
  { name: 'Volkhov', category: 'serif', weights: [400, 700] },
  { name: 'Gelasio', category: 'serif' },
  { name: 'EB Garamond', category: 'serif' },
  { name: 'Cormorant Garamond', category: 'serif', weights: [400, 500, 600, 700] },
  { name: 'Libre Baskerville', category: 'serif', weights: [400, 700] },
  { name: 'Spectral', category: 'serif' },

  // — Mono —
  { name: 'JetBrains Mono', category: 'mono' },
  { name: 'IBM Plex Mono', category: 'mono' },
  { name: 'Source Code Pro', category: 'mono' },

  // — Display (great for name headers) —
  { name: 'Oswald', category: 'display' },
  { name: 'Bebas Neue', category: 'display', weights: [400] },
  { name: 'Abril Fatface', category: 'display', weights: [400] },
  { name: 'Archivo', category: 'display' },

  // — Handwriting / signature (decorative name fonts) —
  { name: 'Dancing Script', category: 'handwriting', weights: [400, 500, 600, 700] },
  { name: 'Dynalight', category: 'handwriting', weights: [400] },
  { name: 'Ms Madi', category: 'handwriting', weights: [400], family: 'Ms Madi' },
  { name: 'Meow Script', category: 'handwriting', weights: [400] },
]

const FALLBACKS: Record<FontCategory, string> = {
  sans: 'ui-sans-serif, system-ui, -apple-system, sans-serif',
  serif: 'ui-serif, Georgia, Cambria, "Times New Roman", serif',
  mono: 'ui-monospace, SFMono-Regular, Menlo, monospace',
  display: 'ui-sans-serif, system-ui, sans-serif',
  handwriting: 'cursive',
}

export const FONT_MAP: Record<string, FontDef> = Object.fromEntries(FONTS.map((f) => [f.name, f]))

/**
 * Bundled families that draw the scripts a Latin-only family cannot, one
 * chain per category: the category's own face first (a serif résumé keeps a
 * serif Cyrillic), then Inter, which covers Cyrillic, Greek and Vietnamese
 * in full. These sit in the CSS stack right after the chosen family, so the
 * browser draws a Cyrillic letter with them instead of with whatever system
 * font it finds; the PDF painter walks the same chain (src/lib/pdf/
 * textFallback.ts), so the page and the export agree glyph for glyph.
 */
export const SCRIPT_FALLBACKS: Record<FontCategory, string[]> = {
  sans: ['Inter'],
  serif: ['Source Serif 4', 'Inter'],
  mono: ['Source Code Pro', 'Inter'],
  display: ['Oswald', 'Inter'],
  handwriting: ['Inter'],
}

/** The fallback families for `name`, in order, never naming `name` itself. */
export function scriptFallbacks(name?: string): string[] {
  const def = name ? FONT_MAP[name] : undefined
  const chain = SCRIPT_FALLBACKS[def?.category ?? 'sans']
  return chain.filter((f) => f !== name)
}

export function fontStack(name?: string): string {
  if (!name) return FALLBACKS.sans
  const def = FONT_MAP[name]
  const fb = def ? def.fallback ?? FALLBACKS[def.category] : FALLBACKS.sans
  const chain = scriptFallbacks(name).map((f) => `"${f}"`)
  return [`"${name}"`, ...chain, fb].join(', ')
}

/**
 * No-op kept for API compatibility. Fonts are self-hosted and their @font-face
 * rules ship in the bundle (src/styles/fonts.css), so there is nothing to inject
 * — the browser lazily fetches the (same-origin, service-worker-precached) woff2
 * on first use. Safe to call on every render.
 */
export function ensureFont(_name?: string): void {
  /* fonts are bundled and always available — nothing to do */
}

/**
 * Resolve only once the requested faces are actually rasterizable. The @font-face
 * rules are already registered (bundled CSS), so we just drive `document.fonts.load`
 * for the specific faces and await `fonts.ready`. This guarantees the print/PDF
 * never falls back to a system font.
 */
export async function ensureFontsReady(names: (string | undefined)[]): Promise<void> {
  const real = names.filter((n): n is string => !!n)
  if (typeof document === 'undefined' || !('fonts' in document)) return
  const fonts = (document as Document & { fonts: FontFaceSet }).fonts
  try {
    await Promise.all(
      real.flatMap((n) => [fonts.load(`400 1em "${n}"`), fonts.load(`700 1em "${n}"`)]).map((p) => p.catch(() => undefined))
    )
    await fonts.ready
  } catch {
    /* ignore */
  }
}

export const FONTS_BY_CATEGORY: Record<FontCategory, FontDef[]> = {
  sans: FONTS.filter((f) => f.category === 'sans'),
  serif: FONTS.filter((f) => f.category === 'serif'),
  mono: FONTS.filter((f) => f.category === 'mono'),
  display: FONTS.filter((f) => f.category === 'display'),
  handwriting: FONTS.filter((f) => f.category === 'handwriting'),
}
